---
title: "R Notebook"
output:
  pdf_document:
    toc: yes
---


```{r}
# Necessary libraries
library(mice)
library(fastDummies)
library(neuralnet)
library(caret)
```



```{r}
data <- read.delim(file = 'clinical_bone.tsv', sep = '\t', header = TRUE)
data[data == "\'--"] <- "NULL"
is.na(data) <- data == "NULL"
data <- data[, colSums(is.na(data)) < nrow(data)]
#names(data)
```


```{r, echo=FALSE}
data[data=="not reported"] <- NA
data[data=="Not Reported"] <- NA
data[data=="unknown"] <- NA
data[data=="Unknown"] <- NA
data[data=="not allowed to collect"] <- NA
#summary(data)
```


```{r}
rem <- colSums(is.na(data)) > 1000
```


```{r, echo=FALSE}
data <- subset(data, select = -c(case_id, case_submitter_id))
data <- transform(
  data,
  project_id=as.factor(project_id),
  age_at_index=as.numeric(age_at_index),
  age_is_obfuscated=as.factor(age_is_obfuscated),
  cause_of_death=as.factor(cause_of_death),
  days_to_birth=as.numeric(days_to_birth),
  days_to_death=as.numeric(days_to_death),
  ethnicity=as.factor(ethnicity),
  gender=as.factor(gender),
  race=as.factor(race),
  vital_status=as.factor(vital_status),
  year_of_birth=as.numeric(year_of_birth),
  year_of_death=as.numeric(year_of_death),
  age_at_diagnosis=as.numeric(age_at_diagnosis),
  ann_arbor_b_symptoms=as.factor(ann_arbor_b_symptoms),
  ann_arbor_extranodal_involvement=as.factor(ann_arbor_extranodal_involvement),
  ann_arbor_pathologic_stage=as.factor(ann_arbor_pathologic_stage),
  burkitt_lymphoma_clinical_variant=as.factor(burkitt_lymphoma_clinical_variant),
  classification_of_tumor=as.factor(classification_of_tumor),
  days_to_diagnosis=as.numeric(days_to_diagnosis),
  days_to_last_follow_up=as.numeric(days_to_last_follow_up),
  days_to_last_known_disease_status=as.numeric(days_to_last_known_disease_status),
  inss_stage=as.numeric(inss_stage),
  iss_stage=as.factor(iss_stage),
  last_known_disease_status=as.factor(last_known_disease_status),
  method_of_diagnosis=as.factor(method_of_diagnosis),
  morphology=as.factor(morphology),
  primary_diagnosis=as.factor(primary_diagnosis),
  prior_malignancy=as.factor(prior_malignancy),
  prior_treatment=as.factor(prior_treatment),
  progression_or_recurrence=as.factor(progression_or_recurrence),
  site_of_resection_or_biopsy=as.factor(site_of_resection_or_biopsy),
  synchronous_malignancy=as.factor(synchronous_malignancy),
  tissue_or_organ_of_origin=as.factor(tissue_or_organ_of_origin),
  tumor_grade=as.factor(tumor_grade),
  year_of_diagnosis=as.numeric(year_of_diagnosis),
  days_to_treatment_end=as.numeric(days_to_treatment_end),
  days_to_treatment_start=as.numeric(days_to_treatment_start),
  initial_disease_status=as.factor(initial_disease_status),
  number_of_cycles = as.factor(number_of_cycles),
  regimen_or_line_of_therapy = as.factor(regimen_or_line_of_therapy),
  therapeutic_agents=as.factor(therapeutic_agents),
  treatment_anatomic_site=as.factor(treatment_anatomic_site),
  treatment_dose=as.factor(treatment_dose),
  treatment_intent_type=as.factor(treatment_intent_type),
  treatment_or_therapy=as.factor(treatment_or_therapy),
  treatment_outcome=as.factor(treatment_outcome),
  treatment_type=as.factor(treatment_type)
)
```

```{r}
data <- subset(data, select = -c(age_is_obfuscated, cause_of_death, days_to_death, year_of_birth, year_of_death, ann_arbor_b_symptoms, ann_arbor_extranodal_involvement, ann_arbor_pathologic_stage, burkitt_lymphoma_clinical_variant, classification_of_tumor, days_to_diagnosis, inss_stage, last_known_disease_status, method_of_diagnosis, prior_malignancy, prior_treatment, progression_or_recurrence, synchronous_malignancy, tumor_grade, year_of_diagnosis, days_to_treatment_end, days_to_treatment_start, initial_disease_status, number_of_cycles, regimen_or_line_of_therapy, therapeutic_agents, treatment_anatomic_site, treatment_dose, treatment_intent_type, treatment_or_therapy, treatment_outcome, treatment_type))
#summary(data)
```

```{r, echo=FALSE}
data2 <- data[!is.na(data$vital_status), ]

data_imp <- mice(data2, m=5, method = "sample", printFlag = FALSE)
```

```{r}
data_subset_nn <- complete(data_imp)
#summary(data_subset_nn)
```

```{r}
data_subset_nn <- subset(data_subset_nn, select = -c(morphology, primary_diagnosis))
names(data_subset_nn)
```

```{r}

# project_id=as.factor(project_id)                                                <== "factored variable"
# age_at_index=as.numeric(age_at_index)
# days_to_birth=as.numeric(days_to_birth)
# ethnicity=as.factor(ethnicity)                                                  <== "factored variable"
# gender=as.factor(gender)                                                        <== "factored variable"
# race=as.factor(race)                                                            <== "factored variable"
# vital_status=as.factor(vital_status)                                            <== "factored variable"
# age_at_diagnosis=as.numeric(age_at_diagnosis)
# days_to_last_follow_up=as.numeric(days_to_last_follow_up)
# days_to_last_known_disease_status=as.numeric(days_to_last_known_disease_status)
# iss_stage=as.factor(iss_stage)                                                  <== "factored variable"
# site_of_resection_or_biopsy=as.factor(site_of_resection_or_biopsy)              <== "factored variable"
# tissue_or_organ_of_origin=as.factor(tissue_or_organ_of_origin)                  <== "factored variable"
```


```{r}
unique(data_subset_nn$project_id)
unique(data_subset_nn$ethnicity)
unique(data_subset_nn$gender)
unique(data_subset_nn$race)
unique(data_subset_nn$vital_status)
unique(data_subset_nn$iss_stage)
unique(data_subset_nn$site_of_resection_or_biopsy)
unique(data_subset_nn$tissue_or_organ_of_origin)

```


```{r}
# Factored variables in 'data_subset_nn'
data_subset_nn_factored_vars <- subset(data_subset_nn,
                                       select = c(project_id,
                                                  ethnicity,
                                                  gender,
                                                  race,
                                                  vital_status,
                                                  iss_stage,
                                                  site_of_resection_or_biopsy,
                                                  tissue_or_organ_of_origin))
data_subset_nn_factored_vars_mat <- as.matrix(data_subset_nn_factored_vars)

# Non-factored variables in 'data_subset_nn'
data_subset_nn_nonfactored_vars <- subset(data_subset_nn,
                                          select = -c(project_id,
                                                      ethnicity,
                                                      gender,
                                                      race,
                                                      vital_status,
                                                      iss_stage,
                                                      site_of_resection_or_biopsy,
                                                      tissue_or_organ_of_origin))
data_subset_nn_nonfactored_vars_mat <- as.matrix(data_subset_nn_nonfactored_vars)

```


```{r}




dummies <- fastDummies::dummy_cols(data_subset_nn_factored_vars)
dummies <- subset(dummies, select = -c(1:length(names(data_subset_nn_factored_vars))))

```


```{r}
normalize <- function(matrix_x) {
  n = length(matrix_x[,1])
  return(apply(matrix_x, 2, rank) / (n + 1))
}
data_subset_nn_nonfactored_vars_mat_normalized <- normalize(data_subset_nn_nonfactored_vars_mat)
```


```{r}
data_subset_nn_normalized <- cbind(data_subset_nn_nonfactored_vars_mat_normalized, dummies)
data_subset_nn_normalized <- subset(data_subset_nn_normalized,
                                    select = -c(`vital_status_Dead`))
```


```{r}
names(data_subset_nn_normalized) <- c(
  "age_at_index",
  "days_to_birth",
  "age_at_diagnosis",
  "days_to_last_follow_up",
  "days_to_last_known_disease_status",
  "project_id_BEATAML1.0_COHORT",
  "project_id_BEATAML1.0_CRENOLANIB",
  "project_id_CGCI_BLGSP",
  "project_id_GENIE_DFCI",
  "project_id_GENIE_JHU",
  "project_id_GENIE_MDA",
  "project_id_GENIE_MSK",
  "project_id_GENIE_UHN",
  "project_id_GENIE_VICC",
  "project_id_MMRF_COMMPASS",
  "project_id_OHSU_CNL",
  "project_id_TARGET_ALL_P1",
  "project_id_TARGET_ALL_P2",
  "project_id_TARGET_ALL_P3",
  "project_id_TARGET_AML",
  "project_id_TARGET_NBL",
  "project_id_TCGA_LAML",
  "ethnicity_hispanic",
  "ethnicity_not_hispanic",
  "gender_female",
  "gender_male",
  "race_ameri_ind_or_alaska",
  "race_asian",
  "race_black_or_afr_ameri",
  "race_hawaiian_or_pacific_islander",
  "race_other",
  "race_white",
  "vital_status_Alive",
  "iss_stage_I",
  "iss_stage_II",
  "iss_stage_III",
  "site_of_resection_or_biopsy_Abdomen_NOS",
  "site_of_resection_or_biopsy_Blood",
  "site_of_resection_or_biopsy_Bone_marrow",
  "site_of_resection_or_biopsy_Bones_of_skull_and_face",
  "site_of_resection_or_biopsy_Cheek_mucosa",
  "site_of_resection_or_biopsy_Connective_and_other_soft_tissues",
  "site_of_resection_or_biopsy_Connective_and_other_soft_tissues_NOS",
  "site_of_resection_or_biopsy_Head_face_or_neck_NOS",
  "site_of_resection_or_biopsy_Hematopoietic_system_NOS",
  "site_of_resection_or_biopsy_Intra_abdominal_lymph_nodes",
  "site_of_resection_or_biopsy_Kidney_NOS",
  "site_of_resection_or_biopsy_Lip_NOS",
  "site_of_resection_or_biopsy_Liver",
  "site_of_resection_or_biopsy_Lower_gum",
  "site_of_resection_or_biopsy_Lymph_nodes_of_head_face_neck",
  "site_of_resection_or_biopsy_Mandible",
  "site_of_resection_or_biopsy_Mouth_NOS",
  "site_of_resection_or_biopsy_Ovary",
  "site_of_resection_or_biopsy_Pelvis_NOS",
  "site_of_resection_or_biopsy_Peritoneum_NOS",
  "site_of_resection_or_biopsy_Retroperitoneum",
  "site_of_resection_or_biopsy_Small_intestine_NOS",
  "site_of_resection_or_biopsy_Specified_parts_of_peritoneum",
  "site_of_resection_or_biopsy_Spleen",
  "site_of_resection_or_biopsy_Testis_NOS",
  "site_of_resection_or_biopsy_Vestibule_of_mouth",
  "tissue_or_organ_of_origin_Bone_marrow",
  "tissue_or_organ_of_origin_Bones_of_skull_and_face",
  "tissue_or_organ_of_origin_Hematopoietic_system_NOS",
  "tissue_or_organ_of_origin_Orbit_NOS"
)


```



```{r}
train_ind <- sample(seq_len(nrow(data_subset_nn_normalized)),
                    size = floor(0.7 * nrow(data_subset_nn_normalized)))

train_nn <- data_subset_nn_normalized[train_ind,]
test_nn <- data_subset_nn_normalized[-train_ind,]

# Temporarily removing numeric variables
train_nn_temp <- subset(train_nn, select = -c(1:5))
test_nn_temp <- subset(test_nn, select = -c(1:5))
```


```{r}
## Neural Network
## (https://datascienceplus.com/neuralnet-train-and-test-neural-networks-using-r/)
## (http://uc-r.github.io/ann_classification)

# Making the neural network model
nn <- neuralnet(vital_status_Alive ~ project_id_BEATAML1.0_COHORT + project_id_BEATAML1.0_CRENOLANIB + project_id_CGCI_BLGSP + project_id_GENIE_DFCI + project_id_GENIE_JHU + project_id_GENIE_MDA + project_id_GENIE_MSK + project_id_GENIE_UHN + project_id_GENIE_VICC + project_id_MMRF_COMMPASS +  project_id_OHSU_CNL + project_id_TARGET_ALL_P1 + project_id_TARGET_ALL_P2 + project_id_TARGET_ALL_P3 + project_id_TARGET_AML + project_id_TARGET_NBL + project_id_TCGA_LAML + ethnicity_hispanic + ethnicity_not_hispanic + gender_female + gender_male + race_ameri_ind_or_alaska + race_asian +  race_black_or_afr_ameri + race_hawaiian_or_pacific_islander + race_other + race_white + iss_stage_I + iss_stage_II + iss_stage_III + site_of_resection_or_biopsy_Abdomen_NOS + site_of_resection_or_biopsy_Blood + site_of_resection_or_biopsy_Bone_marrow + site_of_resection_or_biopsy_Bones_of_skull_and_face + site_of_resection_or_biopsy_Cheek_mucosa + site_of_resection_or_biopsy_Connective_and_other_soft_tissues + site_of_resection_or_biopsy_Connective_and_other_soft_tissues_NOS + site_of_resection_or_biopsy_Head_face_or_neck_NOS + site_of_resection_or_biopsy_Hematopoietic_system_NOS + site_of_resection_or_biopsy_Intra_abdominal_lymph_nodes + site_of_resection_or_biopsy_Kidney_NOS + site_of_resection_or_biopsy_Lip_NOS + site_of_resection_or_biopsy_Liver + site_of_resection_or_biopsy_Lower_gum + site_of_resection_or_biopsy_Lymph_nodes_of_head_face_neck + site_of_resection_or_biopsy_Mandible + site_of_resection_or_biopsy_Mouth_NOS + site_of_resection_or_biopsy_Ovary + site_of_resection_or_biopsy_Pelvis_NOS + site_of_resection_or_biopsy_Peritoneum_NOS + site_of_resection_or_biopsy_Retroperitoneum + site_of_resection_or_biopsy_Small_intestine_NOS + site_of_resection_or_biopsy_Specified_parts_of_peritoneum + site_of_resection_or_biopsy_Spleen + site_of_resection_or_biopsy_Testis_NOS + site_of_resection_or_biopsy_Vestibule_of_mouth + tissue_or_organ_of_origin_Bone_marrow + tissue_or_organ_of_origin_Bones_of_skull_and_face + tissue_or_organ_of_origin_Hematopoietic_system_NOS + tissue_or_organ_of_origin_Orbit_NOS,
                data=train_nn_temp,
                hidden=c(50, 10),#c(50, 10),
                linear.output=FALSE,
                threshold=0.01)

plot(nn)
```


```{r}
nn$result.matrix
```



```{r}
# Testing the resulting output
prediction_threshold <- 0.5
nn.results <- compute(nn, test_nn_temp)

prediction <- nn.results$net.result
prediction[prediction >= prediction_threshold] <- 1
prediction[prediction < prediction_threshold] <- 0
prediction <- c(prediction)
actual <- test_nn$vital_status_Alive

confusionMatrix(factor(prediction), factor(actual))
```

