---
title: "R Notebook"
output: html_notebook
---
```{r}
data <- read.delim(file = 'clinical_bone.tsv', sep = '\t', header = TRUE)
data[data == "\'--"] <- "NULL"
is.na(data) <- data == "NULL"
data <- data[, colSums(is.na(data)) < nrow(data)]
```


```{r}
#names(data)
```


```{r}
data <- subset(data, select = -c(case_id, case_submitter_id))
data <- transform(
  data,
  project_id=as.factor(project_id),
  age_at_index=as.numeric(age_at_index),
  age_is_obfuscated=as.factor(age_is_obfuscated),
  cause_of_death=as.factor(cause_of_death),
  days_to_birth=as.numeric(days_to_birth),
  days_to_death=as.numeric(days_to_death),
  ethnicity=as.factor(ethnicity),
  gender=as.factor(gender),
  race=as.factor(race),
  vital_status=as.factor(vital_status),
  year_of_birth=as.numeric(year_of_birth),
  year_of_death=as.numeric(year_of_death),
  age_at_diagnosis=as.numeric(age_at_diagnosis),
  ann_arbor_b_symptoms=as.factor(ann_arbor_b_symptoms),
  ann_arbor_extranodal_involvement=as.factor(ann_arbor_extranodal_involvement),
  ann_arbor_pathologic_stage=as.factor(ann_arbor_pathologic_stage),
  burkitt_lymphoma_clinical_variant=as.factor(burkitt_lymphoma_clinical_variant),
  classification_of_tumor=as.factor(classification_of_tumor),
  days_to_diagnosis=as.numeric(days_to_diagnosis),
  days_to_last_follow_up=as.numeric(days_to_last_follow_up),
  days_to_last_known_disease_status=as.numeric(days_to_last_known_disease_status),
  inss_stage=as.numeric(inss_stage),
  iss_stage=as.factor(iss_stage),
  last_known_disease_status=as.factor(last_known_disease_status),
  method_of_diagnosis=as.factor(method_of_diagnosis),
  morphology=as.factor(morphology),
  primary_diagnosis=as.factor(primary_diagnosis),
  prior_malignancy=as.factor(prior_malignancy),
  prior_treatment=as.factor(prior_treatment),
  progression_or_recurrence=as.factor(progression_or_recurrence),
  site_of_resection_or_biopsy=as.factor(site_of_resection_or_biopsy),
  synchronous_malignancy=as.factor(synchronous_malignancy),
  tissue_or_organ_of_origin=as.factor(tissue_or_organ_of_origin),
  tumor_grade=as.factor(tumor_grade),
  year_of_diagnosis=as.numeric(year_of_diagnosis),
  days_to_treatment_end=as.numeric(days_to_treatment_end),
  days_to_treatment_start=as.numeric(days_to_treatment_start),
  initial_disease_status=as.factor(initial_disease_status),
  number_of_cycles = as.factor(number_of_cycles),
  regimen_or_line_of_therapy = as.factor(regimen_or_line_of_therapy),
  therapeutic_agents=as.factor(therapeutic_agents),
  treatment_anatomic_site=as.factor(treatment_anatomic_site),
  treatment_dose=as.factor(treatment_dose),
  treatment_intent_type=as.factor(treatment_intent_type),
  treatment_or_therapy=as.factor(treatment_or_therapy),
  treatment_outcome=as.factor(treatment_outcome),
  treatment_type=as.factor(treatment_type)
  )
```

```{r}
data[data=="not reported"] <- NA
data[data=="Not Reported"] <- NA
data[data=="unknown"] <- NA
data[data=="Unknown"] <- NA
data[data=="not allowed to collect"] <- NA
summary(data)
```

```{r}
rem <- colSums(is.na(data)) > 1000
```


```{r}
data <- subset(data, select = -c(age_is_obfuscated, cause_of_death, days_to_death, year_of_birth, year_of_death, ann_arbor_b_symptoms, ann_arbor_extranodal_involvement, ann_arbor_pathologic_stage, burkitt_lymphoma_clinical_variant, classification_of_tumor, days_to_diagnosis, inss_stage, last_known_disease_status, method_of_diagnosis, prior_malignancy, prior_treatment, progression_or_recurrence, synchronous_malignancy, tumor_grade, year_of_diagnosis, days_to_treatment_end, days_to_treatment_start, initial_disease_status, number_of_cycles, regimen_or_line_of_therapy, therapeutic_agents, treatment_anatomic_site, treatment_dose, treatment_intent_type, treatment_or_therapy, treatment_outcome, treatment_type))

summary(data)
```

```{r}
data2 <- data[!is.na(data$vital_status), ]
library(mice)
data_imp <- mice(data2, m=5, method = "sample", printFlag = FALSE)
```

```{r}
data_subset_rf <- complete(data_imp)
summary(data_subset_rf)
```

```{r}
data_subset_rf <- subset(data_subset_rf, select = -c(morphology, primary_diagnosis))
```


```{r}
library(randomForest)
library(caTools)
library(caret)
sample <- sample.split(data_subset_rf$vital_status, SplitRatio = .7)
train_rf <- subset(data_subset_rf, sample == TRUE)
test_rf  <- subset(data_subset_rf, sample == FALSE)
#dim(train_rf)
#dim(test_rf)
train_rf$vital_status <- factor(train_rf$vital_status)
test_rf$vital_status <- factor(test_rf$vital_status)
rf <- randomForest(vital_status ~ ., data=train_rf, na.action = na.omit)
```

```{r}
p1 <- predict(rf, train_rf)
confusionMatrix(p1, train_rf$vital_status)
p2 <- predict(rf, test_rf)
confusionMatrix(p2, test_rf$vital_status)
```


