---
title: "Untitled"
author: ""
date: ""
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(survival)
library(ranger)
library(ggplot2)
library(dplyr)
library(ggfortify)
library(survminer)
```


```{r}
data <- read.delim(file = 'clinical.tsv', sep = '\t', header = TRUE)
###dont forget to load clinical dataset

data[data == "\'--"] <- "NULL"
is.na(data) <- data == "NULL"
data <- data[, colSums(is.na(data)) < nrow(data)]
```

```{r}
smp_size <- floor(0.7 * nrow(data))
rand_indexes <- sample(seq_len(nrow(data)), size = smp_size)
data_subset_1 <- data[rand_indexes,] # for survival analysis
#data_subset_2 <- data[-rand_indexes,] # for machine learning modeling and analysis
```

```{r}
data_subset_1 <- subset(data_subset_1, select = -c(case_id, case_submitter_id))
data_subset_1 <- transform(
  data_subset_1,
  project_id=as.factor(project_id),
  age_at_index=as.numeric(age_at_index),
  age_is_obfuscated=as.factor(age_is_obfuscated),
  cause_of_death=as.factor(cause_of_death),
  days_to_birth=as.numeric(days_to_birth),
  days_to_death=as.numeric(days_to_death),
  ethnicity=as.factor(ethnicity),
  gender=as.factor(gender),
  race=as.factor(race),
  vital_status=as.factor(vital_status),
  year_of_birth=as.numeric(year_of_birth),
  year_of_death=as.numeric(year_of_death),
  age_at_diagnosis=as.numeric(age_at_diagnosis),
  ajcc_pathologic_stage=as.factor(ajcc_pathologic_stage),
  ajcc_staging_system_edition=as.factor(ajcc_staging_system_edition),
  classification_of_tumor=as.factor(classification_of_tumor),
  days_to_diagnosis=as.numeric(days_to_diagnosis),
  days_to_last_follow_up=as.numeric(days_to_last_follow_up),
  days_to_last_known_disease_status=as.numeric(days_to_last_known_disease_status),
  days_to_recurrence=as.numeric(days_to_recurrence),
  icd_10_code=as.factor(icd_10_code),
  last_known_disease_status=as.factor(last_known_disease_status),
  metastasis_at_diagnosis=as.factor(metastasis_at_diagnosis),
  morphology=as.factor(morphology),
  primary_diagnosis=as.factor(primary_diagnosis),
  prior_malignancy=as.factor(prior_malignancy),
  prior_treatment=as.factor(prior_treatment),
  progression_or_recurrence=as.factor(progression_or_recurrence),
  residual_disease=as.factor(residual_disease),
  site_of_resection_or_biopsy=as.factor(site_of_resection_or_biopsy),
  synchronous_malignancy=as.factor(synchronous_malignancy),
  tissue_or_organ_of_origin=as.factor(tissue_or_organ_of_origin),
  tumor_grade=as.factor(tumor_grade),
  year_of_diagnosis=as.numeric(year_of_diagnosis),
  days_to_treatment_end=as.numeric(days_to_treatment_end),
  days_to_treatment_start=as.numeric(days_to_treatment_start),
  initial_disease_status=as.factor(initial_disease_status),
  therapeutic_agents=as.factor(therapeutic_agents),
  treatment_anatomic_site=as.factor(treatment_anatomic_site),
  treatment_intent_type=as.factor(treatment_intent_type),
  treatment_or_therapy=as.factor(treatment_or_therapy),
  treatment_outcome=as.factor(treatment_outcome),
  treatment_type=as.factor(treatment_type)
 )
  

#head(data_subset_1)
```

# Analysis

## Survival Analysis

We first conducted some survival analysis on the half of the initial preprocessed dataset.

```{r}
data_subset_1$vital_status<-if_else(data_subset_1$vital_status == "Alive",0,1)

data_subset_1$treatment_or_therapy[data_subset_1$treatment_or_therapy=="not reported"]<-NA
data_subset_1$treatment_or_therapy[data_subset_1$treatment_or_therapy=="unknown"]<-NA

data_subset_1$gender[data_subset_1$gender=="not reported"]<-NA

data_subset_1$race[data_subset_1$race=="not allowed to collect"]<-NA
data_subset_1$race[data_subset_1$race=="not reported"]<-NA
data_subset_1$race[data_subset_1$race=="other"]<-NA
data_subset_1$race[data_subset_1$race=="Unknown"]<-NA
data_subset_1$race[data_subset_1$race=="american indian or alaska native"]<-NA

data_subset_1$ethnicity[data_subset_1$ethnicity=="not allowed to collect"]<-NA
data_subset_1$ethnicity[data_subset_1$ethnicity=="not reported"]<-NA
data_subset_1$ethnicity[data_subset_1$ethnicity=="Unknown"]<-NA

data_subset_1$prior_treatment[data_subset_1$prior_treatment=="Not Reported"]<-NA

data_subset_1$icd_10_code<-ifelse(data_subset_1$icd_10_code == "C71.9","C71.9","C71.0")

data_subset_1$agecat<-data_subset_1$age_at_index
data_subset_1$agecat[data_subset_1$agecat >100 ]<-NA
data_subset_1$agecat[data_subset_1$age_at_index>0&data_subset_1$age_at_index<31]<-"30yo or younger"
data_subset_1$agecat[data_subset_1$age_at_index>30&data_subset_1$age_at_index<51]<-"30yo - 50yo"
data_subset_1$agecat[data_subset_1$age_at_index>50&data_subset_1$age_at_index<71]<-"50yo - 70 yo"
data_subset_1$agecat[data_subset_1$age_at_index>70]<- "70+ yo"
data_subset_1$agecat<-as.factor(data_subset_1$agecat)

data_subset_1$treatment_or_therapy<-droplevels(data_subset_1$treatment_or_therapy)
data_subset_1$gender<-droplevels(data_subset_1$gender)
data_subset_1$race<-droplevels(data_subset_1$race)
data_subset_1$ethnicity<-droplevels(data_subset_1$ethnicity)
data_subset_1$prior_treatment<-droplevels(data_subset_1$prior_treatment)
data_subset_1$agecat<-droplevels(data_subset_1$agecat)



#vars<-c("vital_status","ethnicity","gender","days_to_last_follow_up","age_at_index","race","icd_10_code","treatment_type","treatment_or_therapy")
#mdata<-data_subset_1[vars]

```